### ISSUE TITLE
xhr adapter doesn't set Content-Type when POSTing JSON

### ISSUE THREAD

**Issue by atombender** [bengler/pebbles-client.js#2]
Without this header, Node.js's Express `body-parser` will not recognize the body as JSON. Seems silly to have to enable it explicitly when the default is to stringify JSON arguments.

(Note: The header seems to be implicitly set by some browsers, but not in all, such as Internet Explorer.)

**Comment by bjoerge** [comment]
Is this still relevant?

**Comment by atombender** [comment]
Yep!

**Comment by atombender** [comment]
Actually, no.
